version: "3"

services:
  postgres-db:
    build: ./postgres-db
    volumes:
      - ./postgres-db/pgdata/pgdata
    ports:
      - 7557:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
      - POSTGRES_DB=test_db